In [19]:
# Dependencies
import pandas as pd
import numpy as np

In [20]:
# Load file and Read into CSV
purchase_list = "purchase_data.csv"

purchase_data = pd.read_csv(purchase_list)
purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
5,5,Yalae81,22,Male,81,Dreamkiss,3.61
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67
8,8,Undjask33,22,Male,21,Souleater,1.10
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89
16,16,Lisirra25,20,Male,40,Second Chance,2.52
17,17,Zontibe81,21,Male,161,Devine,1.76
18,18,Reunasu60,22,Female,82,Nirvana,4.90
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81
23,23,Eyrian71,40,Male,151,Severance,3.40
24,24,Siala43,30,Male,141,Persuasion,3.19
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
26,26,Lirtossa84,11,Male,71,Demise,1.61
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16
...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15
756,756,Ilast79,20,Male,73,Ritual Mace,2.05
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60
758,758,Iral74,21,Male,182,Toothpick,4.03
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70
762,762,Asur53,26,Male,110,Suspension,1.44
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07
765,765,Irith83,18,Male,130,Alpha,2.07
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14
767,767,Ilmol66,8,Female,92,Final Critic,4.88
768,768,Assassasta79,38,Male,92,Final Critic,4.88
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58
770,770,Lirtosia63,34,Male,12,Dawne,1.02
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02
774,774,Jiskjask80,11,Male,101,Final Critic,4.19
775,775,Aethedru70,21,Female,60,Wolf,3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,101,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60

# Player Count
Total Number of Players

In [21]:
# Find total number of players
total_players = len(purchase_data["SN"].value_counts())

# Make data frame for total amount of players
player_count = pd.DataFrame({"Total Players":[total_players]})
player_count

   Total Players
0            576

# Purchasing Analysis (Total)
- Number of Unique items
- Average Purchase Price
- Total Number of Purchases
- Total Revenue

In [29]:
unique_items_total = len((purchase_data["Item ID"]).unique())
average_purchase_price = (purchase_data["Price"]).mean()
purchase_number_total = (purchase_data["Purchase ID"]).count()
total_revenue = (purchase_data["Price"]).sum()

#Make Data Frame
summary_df = pd.DataFrame({"Number of Unique Items":[unique_items_total], 
                           "Average Purchase Price":[average_purchase_price], 
                           "Total Number of Purchases":[purchase_number_total], 
                           "Total Revenue": [total_revenue]})
# Format Currency Style
summary_df.style.format({'Average Purchase Price':"${:,.2f}",
                          'Total Revenue':'${:,.2f}'})

# Gender Demographics
- Percentage and Count of Male Players
- Percentage and Count of Female Players
- Percentage and Count of Other / Non-Disclosed

In [32]:
# Group purchase data by gender
gender_data = purchase_data.groupby("Gender")

# Count "SN" total by gender
gender_count = gender_data.nunique()["SN"]

# Divide the total amount of gender by the total amount of players
player_percentage = gender_count / total_players * 100

# Make data frame with previous value
gender_info = pd.DataFrame({"Percentage of Players": player_percentage, 
                            "Total Count": gender_count})
# Format the frame
gender_info.index.name=None

# Format the values
gender_info.sort_values(["Total Count"], ascending = False).style.format({"Percentage of Players":"{:,.2f}"})

# Purchasing Analysis (Gender)
 
- Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender


- Create a summary data frame to hold the results


- Optional: give the displayed data cleaner formatting


- Display the summary data frame

In [26]:
# Count total purchases by gender
total_purchase = gender_data["Purchase ID"].count()

# Average purchase price by gender
avg_purchase_price = gender_data["Price"].mean()

# Average Purchase Total by gender
avg_purchase_total = gender_data["Price"].sum()

# Average purchase total divided by purchase count 
avg_purchase_per_person = avg_purchase_total / gender_count

# Create dataframe with values
gender_info = pd.DataFrame({"Purchase Count": total_purchase, 
                            "Average Purchase Price": avg_purchase_price, 
                            "Average Purchase Value": avg_purchase_total, 
                            "Average Purchase Total Per Person": avg_purchase_per_person})

# Put gender in top left corner of frame
gender_info.index.name = "Gender"

# Format with currency
gender_info.style.format({"Average Purchase Value": "${:,.2f}",
                          "Average Purchase Price": "${:,.2f}",
                          "Average Purchase Total Per Person": "{:,.2f}"})

In [39]:
# Group ages
age_bins = [0, 9.9, 14.9, 19.9, 24.9, 29.9, 34.9, 39.9, 9999]
group_names = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "<=40"]

# Sort values into bins
purchase_data["Age Group"] = pd.cut(purchase_data["Age"], age_bins, labels=group_names)
purchase_data

# Create new dataframe and add "Age Group" to it
age_group = purchase_data.groupby("Age Group")

# Count total players by age category
total_age_count = age_group["SN"].nunique()

# Calculate percentages by age
age_percentage = (total_age_count/total_players) * 100

# Create dataframe with values
age_info = pd.DataFrame({"Percentage of Players": age_percentage, 
                         "Total Count": total_age_count})

# Format dataframe with no name in corner
age_info.index.name = None

# Format percentage 
age_info.style.format({"Percentage of Players":"{:,.2f}"})

# Purchasing Analysis (Age)
 - Bin the purchase_data data frame by age


- Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


- Create a summary data frame to hold the results


- Optional: give the displayed data cleaner formatting


- Display the summary data frame

In [46]:
# Count purchases by age group
age_purchase_count = age_group["Purchase ID"].count()

# Find average purchase price by age group
avg_purchase_price_age = age_group["Price"].mean()

# Find total purchase value by age group
total_purchase_value = age_group["Price"].sum()

# Find total average purchase per person 
avg_purchase_per_person = total_purchase_value / total_age_count

# Make DataFrame
age_info = pd.DataFrame({"Purchase Count": age_purchase_count, 
                         "Average Purchase Price": avg_purchase_price_age, 
                         "Total Purchase Value": total_purchase_value, 
                         "Average Purchase Total Per Person": avg_purchase_per_person})

# Format data frame with no index name
age_info.index.name = None

# Format currency style
age_info.style.format({"Average Purchase Price":"${:,.2f}", 
                       "Total Purchase Value":"${:,.2f}", 
                       "Average Purchase Total Per Person":"${:,.2f}"})

# Top Spenders

- Identify the the top 5 spenders in the game by total purchase value, then list (in a table):

- SN(screen name)

- Purchase Count

- Average Purchase Price

- Total Purchase Value

In [47]:
# Group purchase data by screen name
purchase_stats = purchase_data.groupby("SN")

# Count total purchases by name
purchase_name_count = purchase_stats["Purchase ID"].count()

# Find average purchase by name
avg_purchase_spender = purchase_stats["Price"].mean()

# Find purchase total
total_spender_purchase = purchase_stats["Price"].sum()

# Make data frame with values
top_spenders = pd.DataFrame({"Purchase Count": purchase_name_count, 
                             "Average Purchase Price": avg_purchase_spender, 
                             "Total Purchase Value": total_spender_purchase})

# Sort in descending order to find top 5 spenders
format_spenders = top_spenders.sort_values(["Total Purchase Value"], ascending=False).head()

#Format with currency 
format_spenders.style.format({"Average Purchase Total":"${:,.2f}", 
                              "Average Purchase Price":"${:,.2f}", 
                              "Total Purchase Value":"${:,.2f}"})

#  Most Popular Items
 
- Retrieve the Item ID, Item Name, and Item Price columns

- Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value

- Create a summary data frame to hold the results

- Sort the purchase count column in descending order

- Optional: give the displayed data cleaner formatting

- Display a preview of the summary data frame

In [50]:
# Make new data frame with "items"
items = purchase_data[["Item ID", "Item Name", "Price"]]

# Group "items" by "item id" and "item name"
item_info = items.groupby(["Item ID", "Item Name"])

# Find total amount of times that an item has been purchased
total_items = item_info["Price"].count()

# Find purchase balue per item
purchase_value = (item_info["Price"].sum())

# Find single item price
item_price = purchase_value / total_items

# Make data frame with values
item_info = pd.DataFrame({"Purchase Count": total_items, 
                          "Item Price": item_price, 
                          "Total Purchase Value": purchase_value})

# Sort in descending order to find top 5 spenders and top 5 items 
items_format = item_info.sort_values(["Purchase Count"], ascending=False).head()

# Format with currency Style
items_format.style.format({"Item Price":"${:,.2f}", 
                           "Total Purchase Value":"${:,.2f}"})

# Most Profitable Items

- Top 5 most profitable items by total purchase value:

    - Item ID

    - Item Name

    - Purchase Count

    - Item Price

    - Total Purchase Value

In [ ]:
# Take "item_info" and change the sorting to find the highest total purchase value
items_format = items_info.sort_values(["Total Purchase Value"], ascending=False).head()

# Format with currency style
items_format.style.format({"Item Price":"${:,.2f}", 
                           "Tot"})